### PR TITLE
Ai refactor

### LINKED ISSUE #292: Refactor AI classes
When reviewing some recent changes, I noticed a lot of repeated code across the AI classes. We should be able to pull some of this code into a super class.

### LINKED ISSUE #293: Use Chain-of-Responsibility for AI actions
As it looks like the AI actions are a series of if...then...else if...else if...else if..., we could probably use the chain of responsibility pattern here to make things more flexible and maintainable (and reduce duplicate code).

### LINKED ISSUE #343: AI adding group card bug
**Describe the bug**
A clear and concise description of what the problem is.
Sometimes when the AI adds a group card to a stack we get a NaN playing card. This doesn't seem to happen with non AI players.

**Screenshots**
screenshot 2018-06-19 12 04 42

### PR DESCRIPTION
**Pull request by JaceRiehl**
Fixes #292 
Fixes #293 
Fixes #343 

#### Overview of changes

- Completely refactors the Ai.
- Fixes the bug with the group cards not showing up and creating a glitch in the score when an Ai plays a group card.

Reviewer: @johnanvik

### CODE REVIEW

File: src/classes/AiActions/AiMove.js [hunk 1]
```diff
@@ -68,10 +68,12 @@ export default class {
 
   getStackToRepeat (e) {
     let stackToRepeat
-    for (let i = 1; i <= 10; i++) {
-      let tmpStack = e.stack.find(stack => stack.score === i && !stack.maxRepeats() && (stack.stackTopCard().type !== 'R' || stack.stackTopCard().value !== 1))
-      if (tmpStack !== undefined && tmpStack.boolSide === store.getters.getCoinMsg) {
-        stackToRepeat = tmpStack
+    if (e.stack !== undefined) {
+      for (let i = 1; i <= 10; i++) {
+        let tmpStack = e.stack.find(stack => stack.score === i && !stack.maxRepeats() && (stack.stackTopCard().type !== 'R' || stack.stackTopCard().value !== 1))
```
Comment (johnanvik) [inline src/classes/AiActions/AiMove.js]: Consider adding some explaining variables to make this conditional easier to understand.

File: src/classes/AiActions/AiHandler.js [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+      moveList = [this.hack, this.virus, this.powerOutage, this.firewall, this.generator, this.antiVirus, this.overclock, this.batteryBackup, this.variable, this.repeat,
+        this.instruction, this.repeatX, this.group, this.discard]
+    } else if (type === 'sprinter') {
+      moveList = [this.variable, this.overclock, this.repeatX, this.repeat, this.virus, this.firewall, this.generator, this.antiVirus, this.powerOutage, this.batteryBackup,
+        this.instruction, this.hack, this.group, this.instruction, this.discard]
+    } else if (type === 'protector') {
+      moveList = [this.group, this.firewall, this.generator, this.antiVirus, this.overclock, this.virus, this.powerOutage, this.batteryBackup, this.variable,
+        this.repeat, this.instruction, this.repeatX, this.hack, this.instruction, this.discard]
+    }
+    for (let turn in moveList) {
```
Comment (johnanvik) [inline src/classes/AiActions/AiHandler.js]: As `discard` is always the last action, you could remove it from the list and have it as the action if the for loop falls through (i.e. no other action executed)

File: src/classes/AiActions/AiHandler.js [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+  }
+
+  /**
+   * This creates the order of operations for the ai steps and executes them until a step has been chosen.
+   * @param type The type of Ai.
+   */
+  setAi (type) {
+    let moveList = []
+    if (type === 'gambler') {
+      moveList = [this.hack, this.virus, this.powerOutage, this.firewall, this.generator, this.antiVirus, this.overclock,
```
Comment (johnanvik) [inline src/classes/AiActions/AiHandler.js]: `gambler` has the same order of moves as `hacker`. Copy/paste error?

File: src/classes/AiActions/AiHandler.js [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+        this.stackToPlay = moveList[turn].getStack()
+        this.cardToPlay = moveList[turn].getCard()
+        this.opponentToAttack = moveList[turn].getOpponent()
+        this.moveType = moveList[turn].getMove()
+        break
+      }
+    }
+  }
+  getMove () {
+    return this.moveType
```
Comment (johnanvik) [inline src/classes/AiActions/AiHandler.js]: I like this idea of `move type`. I think we can take this a step further in the refactoring. The idea is to put all of the `protection` moves into a single array. The AIs would then always first protect themselves (i.e. go  through this move array) before doing any other moves. 

I think the advantage here is that the order of protection moves will always be the same anyways (or can  easily be changed in the future for all AIs), so we abstract this commonality. This will also help to better highlight the differences in move priorities for different AIs in the code.

What do you  think? Let me know if you need clarification about this.

Comment (JaceRiehl) [reply src/classes/AiActions/AiHandler.js]: This is a good idea. Just to clarify an example of this would be a safetyMoves = [this.firewall, this.generator, this.antiVirus] and then each individual ai's moveList would look something like this: 
moveList = [safetyMoves, protectionMoves, attackMoves, playMoves] and then collapse the 2d array into a 1d array?

Comment (JaceRiehl) [reply src/classes/AiActions/AiHandler.js]: Reading through this again I think I misunderstood. Do you only want the protection/safety card into their own array or other types as well?

Comment (johnanvik) [reply src/classes/AiActions/AiHandler.js]: I was just thinking about refactoring out the safety and protection moves into an array, although you could create an array for each. I think we need to leave the attack and play moves as a single array, as this is where the AIs would vary.

The idea is to have something like this:
```foreach (action : protection/safety)
   if(action) break
foreach(action : attack/play)
   if(action) break
discard

Comment (JaceRiehl) [reply src/classes/AiActions/AiHandler.js]: I think I implemented this correctly in the latest commit. Instead of running a separate for loop for the protection/safety cards I added them to the beginning of the moveList array to avoid repeated code. Let me know if this fixes it.
